seed: 42
data_config:
  dataset_name: heart_disease_dataset_mlp
  force_download: false
  force_preprocess: false
  raw_csv_path: datasets/heart_disease/initial/heart.csv
  processed_path: datasets/heart_disease/processed_mlp
  split_ratios:
    - 0.70
    - 0.15
    - 0.15
  target_column: HeartDisease
  categorical_columns:
    - Sex
    - ChestPainType
    - FastingBS
    - RestingECG
    - ExerciseAngina
    - ST_Slope
  positive_columns:
    - Cholesterol
    - RestingBP
  apply_standardization: true
  dataloader_config:
    batch_size: 64
    num_workers: 0
    pin_memory: True
trainer_config:
  fast_dev_run: false # sanity check if True
  min_epochs: 1
  max_epochs: 50
  check_val_every_n_epoch: 1
  log_every_n_steps: 3
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: true
  default_root_dir: null
  detect_anomaly: false
mlp_config:
  linear_1_dim: 1000
  linear_2_dim: 1000
hyperparameters_config:
  lr: 2e-3
