on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - "*"

jobs:
  CI:
    name: run pre-commit.ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()
